# Generated by Django 5.2.8 on 2026-03-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='clue',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='clue',
            name='index',
            field=models.IntegerField(unique=True),
        ),
    ]
